/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSonsRouteImport } from './routes/admin.sons'
import { Route as AdminSegurancaRouteImport } from './routes/admin.seguranca'
import { Route as AdminPersonalizacaoRouteImport } from './routes/admin.personalizacao'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminPackAutorizacoesRouteImport } from './routes/admin.pack-autorizacoes'
import { Route as AdminModulosRouteImport } from './routes/admin.modulos'
import { Route as AdminLojaProdutosRouteImport } from './routes/admin.loja-produtos'
import { Route as AdminLojaRouteImport } from './routes/admin.loja'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAnimacoesRouteImport } from './routes/admin.animacoes'
import { Route as AdminAjustarCreditosRouteImport } from './routes/admin.ajustar-creditos'
import { Route as AdminResourceRouteImport } from './routes/admin.$resource'
import { Route as AppPromptsRouteImport } from './routes/_app.prompts'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppPacksRouteImport } from './routes/_app.packs'
import { Route as AppLicencasRouteImport } from './routes/_app.licencas'
import { Route as AppCreditosRouteImport } from './routes/_app.creditos'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppAulasRouteImport } from './routes/_app.aulas'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as ApiPublicValidarLicencaRouteImport } from './routes/api/public/validar-licenca'
import { Route as AppPacksSlugRouteImport } from './routes/_app.packs.$slug'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiPublicWebhooksKiwifyRouteImport } from './routes/api/public/webhooks/kiwify'
import { Route as ApiPublicWebhooksCaktoRouteImport } from './routes/api/public/webhooks/cakto'
import { Route as ApiPublicPremiumCoverSplatRouteImport } from './routes/api/public/premium-cover.$'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSonsRoute = AdminSonsRouteImport.update({
  id: '/sons',
  path: '/sons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPersonalizacaoRoute = AdminPersonalizacaoRouteImport.update({
  id: '/personalizacao',
  path: '/personalizacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackAutorizacoesRoute = AdminPackAutorizacoesRouteImport.update({
  id: '/pack-autorizacoes',
  path: '/pack-autorizacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojaProdutosRoute = AdminLojaProdutosRouteImport.update({
  id: '/loja-produtos',
  path: '/loja-produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojaRoute = AdminLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnimacoesRoute = AdminAnimacoesRouteImport.update({
  id: '/animacoes',
  path: '/animacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAjustarCreditosRoute = AdminAjustarCreditosRouteImport.update({
  id: '/ajustar-creditos',
  path: '/ajustar-creditos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourceRoute = AdminResourceRouteImport.update({
  id: '/$resource',
  path: '/$resource',
  getParentRoute: () => AdminRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPacksRoute = AppPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AppRoute,
} as any)
const AppLicencasRoute = AppLicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditosRoute = AppCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAulasRoute = AppAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicValidarLicencaRoute = ApiPublicValidarLicencaRouteImport.update({
  id: '/api/public/validar-licenca',
  path: '/api/public/validar-licenca',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPacksSlugRoute = AppPacksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppPacksRoute,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksKiwifyRoute = ApiPublicWebhooksKiwifyRouteImport.update({
  id: '/api/public/webhooks/kiwify',
  path: '/api/public/webhooks/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksCaktoRoute = ApiPublicWebhooksCaktoRouteImport.update({
  id: '/api/public/webhooks/cakto',
  path: '/api/public/webhooks/cakto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPremiumCoverSplatRoute =
  ApiPublicPremiumCoverSplatRouteImport.update({
    id: '/api/public/premium-cover/$',
    path: '/api/public/premium-cover/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agents': typeof AppAgentsRoute
  '/aulas': typeof AppAulasRoute
  '/clientes': typeof AppClientesRoute
  '/creditos': typeof AppCreditosRoute
  '/licencas': typeof AppLicencasRoute
  '/packs': typeof AppPacksRouteWithChildren
  '/perfil': typeof AppPerfilRoute
  '/prompts': typeof AppPromptsRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/ajustar-creditos': typeof AdminAjustarCreditosRoute
  '/admin/animacoes': typeof AdminAnimacoesRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/loja-produtos': typeof AdminLojaProdutosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/pack-autorizacoes': typeof AdminPackAutorizacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/personalizacao': typeof AdminPersonalizacaoRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/sons': typeof AdminSonsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/packs/$slug': typeof AppPacksSlugRoute
  '/api/public/validar-licenca': typeof ApiPublicValidarLicencaRoute
  '/api/public/premium-cover/$': typeof ApiPublicPremiumCoverSplatRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agents': typeof AppAgentsRoute
  '/aulas': typeof AppAulasRoute
  '/clientes': typeof AppClientesRoute
  '/creditos': typeof AppCreditosRoute
  '/licencas': typeof AppLicencasRoute
  '/packs': typeof AppPacksRouteWithChildren
  '/perfil': typeof AppPerfilRoute
  '/prompts': typeof AppPromptsRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/ajustar-creditos': typeof AdminAjustarCreditosRoute
  '/admin/animacoes': typeof AdminAnimacoesRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/loja-produtos': typeof AdminLojaProdutosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/pack-autorizacoes': typeof AdminPackAutorizacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/personalizacao': typeof AdminPersonalizacaoRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/sons': typeof AdminSonsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/packs/$slug': typeof AppPacksSlugRoute
  '/api/public/validar-licenca': typeof ApiPublicValidarLicencaRoute
  '/api/public/premium-cover/$': typeof ApiPublicPremiumCoverSplatRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/aulas': typeof AppAulasRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/creditos': typeof AppCreditosRoute
  '/_app/licencas': typeof AppLicencasRoute
  '/_app/packs': typeof AppPacksRouteWithChildren
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/prompts': typeof AppPromptsRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/ajustar-creditos': typeof AdminAjustarCreditosRoute
  '/admin/animacoes': typeof AdminAnimacoesRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/loja-produtos': typeof AdminLojaProdutosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/pack-autorizacoes': typeof AdminPackAutorizacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/personalizacao': typeof AdminPersonalizacaoRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/sons': typeof AdminSonsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/packs/$slug': typeof AppPacksSlugRoute
  '/api/public/validar-licenca': typeof ApiPublicValidarLicencaRoute
  '/api/public/premium-cover/$': typeof ApiPublicPremiumCoverSplatRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/esqueci-senha'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/agents'
    | '/aulas'
    | '/clientes'
    | '/creditos'
    | '/licencas'
    | '/packs'
    | '/perfil'
    | '/prompts'
    | '/admin/$resource'
    | '/admin/ajustar-creditos'
    | '/admin/animacoes'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/loja'
    | '/admin/loja-produtos'
    | '/admin/modulos'
    | '/admin/pack-autorizacoes'
    | '/admin/pagamentos'
    | '/admin/personalizacao'
    | '/admin/seguranca'
    | '/admin/sons'
    | '/admin/usuarios'
    | '/admin/'
    | '/packs/$slug'
    | '/api/public/validar-licenca'
    | '/api/public/premium-cover/$'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/kiwify'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/esqueci-senha'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/agents'
    | '/aulas'
    | '/clientes'
    | '/creditos'
    | '/licencas'
    | '/packs'
    | '/perfil'
    | '/prompts'
    | '/admin/$resource'
    | '/admin/ajustar-creditos'
    | '/admin/animacoes'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/loja'
    | '/admin/loja-produtos'
    | '/admin/modulos'
    | '/admin/pack-autorizacoes'
    | '/admin/pagamentos'
    | '/admin/personalizacao'
    | '/admin/seguranca'
    | '/admin/sons'
    | '/admin/usuarios'
    | '/'
    | '/admin'
    | '/packs/$slug'
    | '/api/public/validar-licenca'
    | '/api/public/premium-cover/$'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/kiwify'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/checkout'
    | '/esqueci-senha'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/_app/agents'
    | '/_app/aulas'
    | '/_app/clientes'
    | '/_app/creditos'
    | '/_app/licencas'
    | '/_app/packs'
    | '/_app/perfil'
    | '/_app/prompts'
    | '/admin/$resource'
    | '/admin/ajustar-creditos'
    | '/admin/animacoes'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/loja'
    | '/admin/loja-produtos'
    | '/admin/modulos'
    | '/admin/pack-autorizacoes'
    | '/admin/pagamentos'
    | '/admin/personalizacao'
    | '/admin/seguranca'
    | '/admin/sons'
    | '/admin/usuarios'
    | '/_app/'
    | '/admin/'
    | '/_app/packs/$slug'
    | '/api/public/validar-licenca'
    | '/api/public/premium-cover/$'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/kiwify'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicValidarLicencaRoute: typeof ApiPublicValidarLicencaRoute
  ApiPublicPremiumCoverSplatRoute: typeof ApiPublicPremiumCoverSplatRoute
  ApiPublicWebhooksCaktoRoute: typeof ApiPublicWebhooksCaktoRoute
  ApiPublicWebhooksKiwifyRoute: typeof ApiPublicWebhooksKiwifyRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sons': {
      id: '/admin/sons'
      path: '/sons'
      fullPath: '/admin/sons'
      preLoaderRoute: typeof AdminSonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seguranca': {
      id: '/admin/seguranca'
      path: '/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/personalizacao': {
      id: '/admin/personalizacao'
      path: '/personalizacao'
      fullPath: '/admin/personalizacao'
      preLoaderRoute: typeof AdminPersonalizacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pack-autorizacoes': {
      id: '/admin/pack-autorizacoes'
      path: '/pack-autorizacoes'
      fullPath: '/admin/pack-autorizacoes'
      preLoaderRoute: typeof AdminPackAutorizacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loja-produtos': {
      id: '/admin/loja-produtos'
      path: '/loja-produtos'
      fullPath: '/admin/loja-produtos'
      preLoaderRoute: typeof AdminLojaProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loja': {
      id: '/admin/loja'
      path: '/loja'
      fullPath: '/admin/loja'
      preLoaderRoute: typeof AdminLojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/animacoes': {
      id: '/admin/animacoes'
      path: '/animacoes'
      fullPath: '/admin/animacoes'
      preLoaderRoute: typeof AdminAnimacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ajustar-creditos': {
      id: '/admin/ajustar-creditos'
      path: '/ajustar-creditos'
      fullPath: '/admin/ajustar-creditos'
      preLoaderRoute: typeof AdminAjustarCreditosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$resource': {
      id: '/admin/$resource'
      path: '/$resource'
      fullPath: '/admin/$resource'
      preLoaderRoute: typeof AdminResourceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/prompts': {
      id: '/_app/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packs': {
      id: '/_app/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof AppPacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/licencas': {
      id: '/_app/licencas'
      path: '/licencas'
      fullPath: '/licencas'
      preLoaderRoute: typeof AppLicencasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creditos': {
      id: '/_app/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AppCreditosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aulas': {
      id: '/_app/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AppAulasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/validar-licenca': {
      id: '/api/public/validar-licenca'
      path: '/api/public/validar-licenca'
      fullPath: '/api/public/validar-licenca'
      preLoaderRoute: typeof ApiPublicValidarLicencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/packs/$slug': {
      id: '/_app/packs/$slug'
      path: '/$slug'
      fullPath: '/packs/$slug'
      preLoaderRoute: typeof AppPacksSlugRouteImport
      parentRoute: typeof AppPacksRoute
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/kiwify': {
      id: '/api/public/webhooks/kiwify'
      path: '/api/public/webhooks/kiwify'
      fullPath: '/api/public/webhooks/kiwify'
      preLoaderRoute: typeof ApiPublicWebhooksKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/cakto': {
      id: '/api/public/webhooks/cakto'
      path: '/api/public/webhooks/cakto'
      fullPath: '/api/public/webhooks/cakto'
      preLoaderRoute: typeof ApiPublicWebhooksCaktoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/premium-cover/$': {
      id: '/api/public/premium-cover/$'
      path: '/api/public/premium-cover/$'
      fullPath: '/api/public/premium-cover/$'
      preLoaderRoute: typeof ApiPublicPremiumCoverSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppPacksRouteChildren {
  AppPacksSlugRoute: typeof AppPacksSlugRoute
}

const AppPacksRouteChildren: AppPacksRouteChildren = {
  AppPacksSlugRoute: AppPacksSlugRoute,
}

const AppPacksRouteWithChildren = AppPacksRoute._addFileChildren(
  AppPacksRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppAulasRoute: typeof AppAulasRoute
  AppClientesRoute: typeof AppClientesRoute
  AppCreditosRoute: typeof AppCreditosRoute
  AppLicencasRoute: typeof AppLicencasRoute
  AppPacksRoute: typeof AppPacksRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppAulasRoute: AppAulasRoute,
  AppClientesRoute: AppClientesRoute,
  AppCreditosRoute: AppCreditosRoute,
  AppLicencasRoute: AppLicencasRoute,
  AppPacksRoute: AppPacksRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminResourceRoute: typeof AdminResourceRoute
  AdminAjustarCreditosRoute: typeof AdminAjustarCreditosRoute
  AdminAnimacoesRoute: typeof AdminAnimacoesRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminLojaRoute: typeof AdminLojaRoute
  AdminLojaProdutosRoute: typeof AdminLojaProdutosRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminPackAutorizacoesRoute: typeof AdminPackAutorizacoesRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPersonalizacaoRoute: typeof AdminPersonalizacaoRoute
  AdminSegurancaRoute: typeof AdminSegurancaRoute
  AdminSonsRoute: typeof AdminSonsRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminResourceRoute: AdminResourceRoute,
  AdminAjustarCreditosRoute: AdminAjustarCreditosRoute,
  AdminAnimacoesRoute: AdminAnimacoesRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLojaRoute: AdminLojaRoute,
  AdminLojaProdutosRoute: AdminLojaProdutosRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminPackAutorizacoesRoute: AdminPackAutorizacoesRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPersonalizacaoRoute: AdminPersonalizacaoRoute,
  AdminSegurancaRoute: AdminSegurancaRoute,
  AdminSonsRoute: AdminSonsRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicValidarLicencaRoute: ApiPublicValidarLicencaRoute,
  ApiPublicPremiumCoverSplatRoute: ApiPublicPremiumCoverSplatRoute,
  ApiPublicWebhooksCaktoRoute: ApiPublicWebhooksCaktoRoute,
  ApiPublicWebhooksKiwifyRoute: ApiPublicWebhooksKiwifyRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
