/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSegurancaRouteImport } from './routes/admin.seguranca'
import { Route as AdminPersonalizacaoRouteImport } from './routes/admin.personalizacao'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminLojaRouteImport } from './routes/admin.loja'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAjustarCreditosRouteImport } from './routes/admin.ajustar-creditos'
import { Route as AdminResourceRouteImport } from './routes/admin.$resource'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppLicencasRouteImport } from './routes/_app.licencas'
import { Route as AppCreditosRouteImport } from './routes/_app.creditos'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppAulasRouteImport } from './routes/_app.aulas'
import { Route as ApiPublicValidarLicencaRouteImport } from './routes/api/public/validar-licenca'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiPublicWebhooksKiwifyRouteImport } from './routes/api/public/webhooks/kiwify'
import { Route as ApiPublicWebhooksCaktoRouteImport } from './routes/api/public/webhooks/cakto'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPersonalizacaoRoute = AdminPersonalizacaoRouteImport.update({
  id: '/personalizacao',
  path: '/personalizacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojaRoute = AdminLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAjustarCreditosRoute = AdminAjustarCreditosRouteImport.update({
  id: '/ajustar-creditos',
  path: '/ajustar-creditos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourceRoute = AdminResourceRouteImport.update({
  id: '/$resource',
  path: '/$resource',
  getParentRoute: () => AdminRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppLicencasRoute = AppLicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditosRoute = AppCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAulasRoute = AppAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicValidarLicencaRoute = ApiPublicValidarLicencaRouteImport.update({
  id: '/api/public/validar-licenca',
  path: '/api/public/validar-licenca',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksKiwifyRoute = ApiPublicWebhooksKiwifyRouteImport.update({
  id: '/api/public/webhooks/kiwify',
  path: '/api/public/webhooks/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksCaktoRoute = ApiPublicWebhooksCaktoRouteImport.update({
  id: '/api/public/webhooks/cakto',
  path: '/api/public/webhooks/cakto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/aulas': typeof AppAulasRoute
  '/clientes': typeof AppClientesRoute
  '/creditos': typeof AppCreditosRoute
  '/licencas': typeof AppLicencasRoute
  '/perfil': typeof AppPerfilRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/ajustar-creditos': typeof AdminAjustarCreditosRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/personalizacao': typeof AdminPersonalizacaoRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/validar-licenca': typeof ApiPublicValidarLicencaRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/aulas': typeof AppAulasRoute
  '/clientes': typeof AppClientesRoute
  '/creditos': typeof AppCreditosRoute
  '/licencas': typeof AppLicencasRoute
  '/perfil': typeof AppPerfilRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/ajustar-creditos': typeof AdminAjustarCreditosRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/personalizacao': typeof AdminPersonalizacaoRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/validar-licenca': typeof ApiPublicValidarLicencaRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/_app/aulas': typeof AppAulasRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/creditos': typeof AppCreditosRoute
  '/_app/licencas': typeof AppLicencasRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/ajustar-creditos': typeof AdminAjustarCreditosRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/personalizacao': typeof AdminPersonalizacaoRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/validar-licenca': typeof ApiPublicValidarLicencaRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/registro'
    | '/aulas'
    | '/clientes'
    | '/creditos'
    | '/licencas'
    | '/perfil'
    | '/admin/$resource'
    | '/admin/ajustar-creditos'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/loja'
    | '/admin/pagamentos'
    | '/admin/personalizacao'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/admin/'
    | '/api/public/validar-licenca'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/kiwify'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/login'
    | '/registro'
    | '/aulas'
    | '/clientes'
    | '/creditos'
    | '/licencas'
    | '/perfil'
    | '/admin/$resource'
    | '/admin/ajustar-creditos'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/loja'
    | '/admin/pagamentos'
    | '/admin/personalizacao'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/'
    | '/admin'
    | '/api/public/validar-licenca'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/kiwify'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/registro'
    | '/_app/aulas'
    | '/_app/clientes'
    | '/_app/creditos'
    | '/_app/licencas'
    | '/_app/perfil'
    | '/admin/$resource'
    | '/admin/ajustar-creditos'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/loja'
    | '/admin/pagamentos'
    | '/admin/personalizacao'
    | '/admin/seguranca'
    | '/admin/usuarios'
    | '/_app/'
    | '/admin/'
    | '/api/public/validar-licenca'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/kiwify'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  ApiPublicValidarLicencaRoute: typeof ApiPublicValidarLicencaRoute
  ApiPublicWebhooksCaktoRoute: typeof ApiPublicWebhooksCaktoRoute
  ApiPublicWebhooksKiwifyRoute: typeof ApiPublicWebhooksKiwifyRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seguranca': {
      id: '/admin/seguranca'
      path: '/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/personalizacao': {
      id: '/admin/personalizacao'
      path: '/personalizacao'
      fullPath: '/admin/personalizacao'
      preLoaderRoute: typeof AdminPersonalizacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loja': {
      id: '/admin/loja'
      path: '/loja'
      fullPath: '/admin/loja'
      preLoaderRoute: typeof AdminLojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ajustar-creditos': {
      id: '/admin/ajustar-creditos'
      path: '/ajustar-creditos'
      fullPath: '/admin/ajustar-creditos'
      preLoaderRoute: typeof AdminAjustarCreditosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$resource': {
      id: '/admin/$resource'
      path: '/$resource'
      fullPath: '/admin/$resource'
      preLoaderRoute: typeof AdminResourceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/licencas': {
      id: '/_app/licencas'
      path: '/licencas'
      fullPath: '/licencas'
      preLoaderRoute: typeof AppLicencasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creditos': {
      id: '/_app/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AppCreditosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aulas': {
      id: '/_app/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AppAulasRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/validar-licenca': {
      id: '/api/public/validar-licenca'
      path: '/api/public/validar-licenca'
      fullPath: '/api/public/validar-licenca'
      preLoaderRoute: typeof ApiPublicValidarLicencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/kiwify': {
      id: '/api/public/webhooks/kiwify'
      path: '/api/public/webhooks/kiwify'
      fullPath: '/api/public/webhooks/kiwify'
      preLoaderRoute: typeof ApiPublicWebhooksKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/cakto': {
      id: '/api/public/webhooks/cakto'
      path: '/api/public/webhooks/cakto'
      fullPath: '/api/public/webhooks/cakto'
      preLoaderRoute: typeof ApiPublicWebhooksCaktoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAulasRoute: typeof AppAulasRoute
  AppClientesRoute: typeof AppClientesRoute
  AppCreditosRoute: typeof AppCreditosRoute
  AppLicencasRoute: typeof AppLicencasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAulasRoute: AppAulasRoute,
  AppClientesRoute: AppClientesRoute,
  AppCreditosRoute: AppCreditosRoute,
  AppLicencasRoute: AppLicencasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminResourceRoute: typeof AdminResourceRoute
  AdminAjustarCreditosRoute: typeof AdminAjustarCreditosRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminLojaRoute: typeof AdminLojaRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPersonalizacaoRoute: typeof AdminPersonalizacaoRoute
  AdminSegurancaRoute: typeof AdminSegurancaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminResourceRoute: AdminResourceRoute,
  AdminAjustarCreditosRoute: AdminAjustarCreditosRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLojaRoute: AdminLojaRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPersonalizacaoRoute: AdminPersonalizacaoRoute,
  AdminSegurancaRoute: AdminSegurancaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  ApiPublicValidarLicencaRoute: ApiPublicValidarLicencaRoute,
  ApiPublicWebhooksCaktoRoute: ApiPublicWebhooksCaktoRoute,
  ApiPublicWebhooksKiwifyRoute: ApiPublicWebhooksKiwifyRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
