import type { ComponentType, SVGProps } from "react";
import {
  KeyRound,
  Users,
  Package,
  Coins,
  Percent,
  Image as ImageIcon,
  Video,
  GraduationCap,
  Megaphone,
  LayoutGrid,
  Store,
  Boxes,
  UserCog,
  Bell,
  Sparkles,
} from "lucide-react";

type IconType = ComponentType<SVGProps<SVGSVGElement>>;

export type FieldType =
  | "text"
  | "textarea"
  | "number"
  | "boolean"
  | "datetime"
  | "select"
  | "select_from_table"
  | "image"
  | "media";

export type Field = {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: { value: string; label: string }[];
  fromTable?: { table: string; labelKey: string; valueKey?: string };
  placeholder?: string;
  step?: number;
  helperText?: string;
};

export type Resource = {
  key: string;
  label: string;
  singular: string;
  table: string;
  icon: IconType;
  fields: Field[];
  listColumns: { key: string; label: string; format?: "text" | "boolean" | "date" | "currency" | "number" }[];
  orderBy?: { column: string; ascending: boolean };
  searchColumns?: string[];
  group?: string;
};

const statusOptions = [
  { value: "ativa", label: "Ativa" },
  { value: "suspensa", label: "Suspensa" },
  { value: "expirada", label: "Expirada" },
  { value: "teste", label: "Teste" },
];

export const resources: Resource[] = [
  {
    key: "licencas",
    label: "Licenças",
    singular: "Licença",
    table: "licencas",
    icon: KeyRound,
    group: "Comercial",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["chave", "plano"],
    fields: [
      { key: "chave", label: "Chave", type: "text", required: true },
      {
        key: "cliente_id",
        label: "Cliente",
        type: "select_from_table",
        fromTable: { table: "clientes", labelKey: "nome" },
      },
      { key: "plano", label: "Plano", type: "text", placeholder: "Ex.: Premium anual" },
      { key: "status", label: "Status", type: "select", options: statusOptions, required: true },
      { key: "expira_em", label: "Expira em", type: "datetime" },
    ],
    listColumns: [
      { key: "chave", label: "Chave" },
      { key: "plano", label: "Plano" },
      { key: "status", label: "Status" },
      { key: "expira_em", label: "Expira", format: "date" },
      { key: "created_at", label: "Criada", format: "date" },
    ],
  },
  {
    key: "clientes",
    label: "Clientes",
    singular: "Cliente",
    table: "clientes",
    icon: Users,
    group: "Comercial",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["nome", "email", "telefone"],
    fields: [
      { key: "nome", label: "Nome", type: "text", required: true },
      { key: "email", label: "E-mail", type: "text" },
      { key: "telefone", label: "Telefone", type: "text" },
      { key: "observacoes", label: "Observações", type: "textarea" },
    ],
    listColumns: [
      { key: "nome", label: "Nome" },
      { key: "email", label: "E-mail" },
      { key: "telefone", label: "Telefone" },
      { key: "created_at", label: "Criado", format: "date" },
    ],
  },
  {
    key: "revendedores",
    label: "Revendedores",
    singular: "Revendedor",
    table: "revendedores",
    icon: UserCog,
    group: "Comercial",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["nome", "email", "telefone"],
    fields: [
      { key: "nome", label: "Nome", type: "text", required: true },
      { key: "email", label: "E-mail", type: "text" },
      { key: "telefone", label: "Telefone", type: "text" },
      { key: "comissao", label: "Comissão (%)", type: "number", step: 0.5 },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "ativo", label: "Ativo" },
          { value: "inativo", label: "Inativo" },
          { value: "pendente", label: "Pendente" },
        ],
      },
      { key: "observacoes", label: "Observações", type: "textarea" },
    ],
    listColumns: [
      { key: "nome", label: "Nome" },
      { key: "email", label: "E-mail" },
      { key: "comissao", label: "Comissão %", format: "number" },
      { key: "status", label: "Status" },
    ],
  },
  {
    key: "produtos",
    label: "Produtos",
    singular: "Produto",
    table: "produtos",
    icon: Package,
    group: "Loja",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["nome"],
    fields: [
      { key: "nome", label: "Nome", type: "text", required: true },
      { key: "descricao", label: "Descrição", type: "textarea" },
      { key: "preco", label: "Preço (R$)", type: "number", step: 0.01, required: true },
      { key: "imagem_url", label: "Imagem", type: "image" },
      { key: "ativo", label: "Ativo", type: "boolean" },
    ],
    listColumns: [
      { key: "nome", label: "Nome" },
      { key: "preco", label: "Preço", format: "currency" },
      { key: "ativo", label: "Ativo", format: "boolean" },
      { key: "created_at", label: "Criado", format: "date" },
    ],
  },
  {
    key: "estoque",
    label: "Estoque",
    singular: "Item de estoque",
    table: "estoque",
    icon: Boxes,
    group: "Loja",
    orderBy: { column: "item", ascending: true },
    searchColumns: ["item"],
    fields: [
      { key: "item", label: "Item", type: "text", required: true },
      {
        key: "produto_id",
        label: "Produto vinculado",
        type: "select_from_table",
        fromTable: { table: "produtos", labelKey: "nome" },
      },
      { key: "quantidade", label: "Quantidade", type: "number", required: true },
      { key: "minimo", label: "Mínimo", type: "number" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "disponivel", label: "Disponível" },
          { value: "baixo", label: "Estoque baixo" },
          { value: "esgotado", label: "Esgotado" },
        ],
      },
      { key: "observacoes", label: "Observações", type: "textarea" },
    ],
    listColumns: [
      { key: "item", label: "Item" },
      { key: "quantidade", label: "Qtd.", format: "number" },
      { key: "minimo", label: "Mínimo", format: "number" },
      { key: "status", label: "Status" },
    ],
  },
  {
    key: "creditos",
    label: "Créditos",
    singular: "Pacote de créditos",
    table: "creditos_packs",
    icon: Coins,
    group: "Loja",
    orderBy: { column: "quantidade", ascending: true },
    searchColumns: ["nome"],
    fields: [
      { key: "nome", label: "Nome", type: "text", required: true },
      { key: "quantidade", label: "Quantidade de créditos", type: "number", required: true },
      { key: "preco", label: "Preço (R$)", type: "number", step: 0.01, required: true },
      { key: "imagem_url", label: "Imagem do pacote", type: "image" },
      {
        key: "badge",
        label: "Etiqueta (ex: PRO, POWER, ESSE SIM)",
        type: "text",
        placeholder: "PRO",
        helperText: "Etiqueta pequena no topo do card (opcional).",
      },
      {
        key: "cor_gradiente",
        label: "Cor / gradiente do card",
        type: "select",
        options: [
          { value: "", label: "Padrão (violeta → laranja)" },
          { value: "violet", label: "Violeta" },
          { value: "magenta", label: "Magenta" },
          { value: "orange", label: "Laranja" },
          { value: "cyan", label: "Ciano" },
          { value: "emerald", label: "Verde" },
          { value: "pink", label: "Rosa" },
          { value: "gold", label: "Dourado" },
          { value: "sunset", label: "Sunset (magenta→laranja)" },
        ],
        helperText: "Define o gradiente colorido do card na Loja.",
      },
      { key: "descricao", label: "Descrição", type: "textarea" },
      { key: "ativo", label: "Ativo", type: "boolean" },
    ],
    listColumns: [
      { key: "nome", label: "Nome" },
      { key: "quantidade", label: "Qtd.", format: "number" },
      { key: "preco", label: "Preço", format: "currency" },
      { key: "ativo", label: "Ativo", format: "boolean" },
    ],
  },
  {
    key: "planos",
    label: "Planos",
    singular: "Plano",
    table: "planos",
    icon: Sparkles,
    group: "Loja",
    orderBy: { column: "preco", ascending: true },
    searchColumns: ["nome"],
    fields: [
      { key: "nome", label: "Nome", type: "text", required: true },
      { key: "preco", label: "Preço (R$)", type: "number", step: 0.01, required: true },
      { key: "creditos_incluidos", label: "Créditos incluídos", type: "number", required: true },
      { key: "duracao_dias", label: "Duração (dias)", type: "number", required: true, helperText: "Ex: 30 = mensal, 365 = anual, 3650 = vitalício." },
      {
        key: "tipo",
        label: "Tipo",
        type: "select",
        options: [
          { value: "mensal", label: "Mensal" },
          { value: "anual", label: "Anual" },
          { value: "vitalicio", label: "Vitalício" },
          { value: "pacote", label: "Pacote" },
        ],
      },
      { key: "imagem_url", label: "Imagem do plano", type: "image" },
      {
        key: "badge",
        label: "Etiqueta (ex: PRO, POWER)",
        type: "text",
        placeholder: "PRO LITE",
        helperText: "Etiqueta pequena no topo do card (opcional).",
      },
      {
        key: "cor_gradiente",
        label: "Cor / gradiente do card",
        type: "select",
        options: [
          { value: "", label: "Padrão (violeta → laranja)" },
          { value: "violet", label: "Violeta" },
          { value: "magenta", label: "Magenta" },
          { value: "orange", label: "Laranja" },
          { value: "cyan", label: "Ciano" },
          { value: "emerald", label: "Verde" },
          { value: "pink", label: "Rosa" },
          { value: "gold", label: "Dourado" },
          { value: "sunset", label: "Sunset (magenta→laranja)" },
        ],
      },
      { key: "descricao", label: "Descrição", type: "textarea" },
      { key: "ativo", label: "Ativo", type: "boolean" },
    ],
    listColumns: [
      { key: "nome", label: "Nome" },
      { key: "preco", label: "Preço", format: "currency" },
      { key: "creditos_incluidos", label: "Créditos", format: "number" },
      { key: "duracao_dias", label: "Dias", format: "number" },
      { key: "ativo", label: "Ativo", format: "boolean" },
    ],
  },
  {
    key: "promocoes",
    label: "Promoções",
    singular: "Promoção",
    table: "promocoes",
    icon: Percent,
    group: "Marketing",
    orderBy: { column: "ordem", ascending: true },
    searchColumns: ["titulo"],
    fields: [
      { key: "titulo", label: "Título", type: "text", required: true },
      { key: "subtitulo", label: "Subtítulo", type: "text" },
      { key: "descricao", label: "Descrição", type: "textarea" },
      { key: "imagem_url", label: "Imagem principal", type: "image" },
      { key: "banner_desktop_url", label: "Banner desktop", type: "image" },
      { key: "banner_mobile_url", label: "Banner mobile", type: "image" },
      { key: "botao_texto", label: "Texto do botão", type: "text", placeholder: "Aproveitar" },
      { key: "link", label: "Link do botão", type: "text", placeholder: "https://…" },
      { key: "preco_antigo", label: "Preço antigo (R$)", type: "number", step: 0.01 },
      { key: "preco_atual", label: "Preço atual (R$)", type: "number", step: 0.01 },
      { key: "desconto_percentual", label: "Desconto (%)", type: "number", step: 0.5 },
      { key: "cor", label: "Cor (ex: violet, magenta, orange)", type: "text" },
      { key: "icone", label: "Ícone (nome lucide)", type: "text", placeholder: "Percent" },
      { key: "ordem", label: "Ordem", type: "number" },
      { key: "destaque", label: "Destaque", type: "boolean" },
      {
        key: "plano_id",
        label: "Plano vinculado (opcional)",
        type: "select_from_table",
        fromTable: { table: "planos", labelKey: "nome" },
      },
      {
        key: "pack_id",
        label: "Pack de créditos vinculado (opcional)",
        type: "select_from_table",
        fromTable: { table: "creditos_packs", labelKey: "nome" },
      },
      { key: "inicio", label: "Data inicial", type: "datetime" },
      { key: "fim", label: "Data final", type: "datetime" },
      { key: "ativo", label: "Ativa", type: "boolean" },
    ],
    listColumns: [
      { key: "titulo", label: "Título" },
      { key: "preco_atual", label: "Preço", format: "currency" },
      { key: "desconto_percentual", label: "Desconto %", format: "number" },
      { key: "ordem", label: "Ordem", format: "number" },
      { key: "ativo", label: "Ativa", format: "boolean" },
      { key: "fim", label: "Fim", format: "date" },
    ],
  },
  {
    key: "carrossel",
    label: "Carrossel",
    singular: "Slide",
    table: "carrossel_slides",
    icon: LayoutGrid,
    group: "Marketing",
    orderBy: { column: "ordem", ascending: true },
    searchColumns: ["titulo"],
    fields: [
      { key: "titulo", label: "Título", type: "text", required: true },
      { key: "subtitulo", label: "Subtítulo", type: "text" },
      { key: "descricao", label: "Descrição", type: "textarea" },
      { key: "imagem_desktop_url", label: "Imagem Desktop", type: "image" },
      { key: "imagem_mobile_url", label: "Imagem Mobile", type: "image" },
      { key: "preco", label: "Preço (R$)", type: "number", step: 0.01 },
      { key: "preco_promocional", label: "Preço promocional (R$)", type: "number", step: 0.01 },
      { key: "botao_texto", label: "Texto do botão", type: "text" },
      { key: "link", label: "Link do botão", type: "text" },
      { key: "cor_botao", label: "Cor do botão", type: "text" },
      { key: "cor_fundo", label: "Cor do fundo", type: "text" },
      { key: "badge", label: "Badge", type: "text" },
      { key: "icone", label: "Ícone (lucide)", type: "text" },
      { key: "ordem", label: "Ordem", type: "number" },
      { key: "inicio", label: "Data início", type: "datetime" },
      { key: "fim", label: "Data fim", type: "datetime" },
      { key: "agendamento", label: "Agendamento", type: "datetime" },
      { key: "ativo", label: "Ativo", type: "boolean" },
    ],
    listColumns: [
      { key: "titulo", label: "Título" },
      { key: "preco_promocional", label: "Promo", format: "currency" },
      { key: "ordem", label: "Ordem", format: "number" },
      { key: "ativo", label: "Ativo", format: "boolean" },
      { key: "fim", label: "Fim", format: "date" },
    ],
  },
  {
    key: "banners",
    label: "Banners",
    singular: "Banner",
    table: "banners",
    icon: LayoutGrid,
    group: "Marketing",
    orderBy: { column: "ordem", ascending: true },
    searchColumns: ["titulo"],
    fields: [
      { key: "titulo", label: "Título", type: "text", required: true },
      { key: "subtitulo", label: "Subtítulo", type: "text" },
      { key: "descricao", label: "Descrição", type: "textarea" },
      { key: "imagem_url", label: "Imagem Desktop", type: "image" },
      { key: "imagem_mobile_url", label: "Imagem Mobile", type: "image" },
      { key: "preco", label: "Preço (R$)", type: "number", step: 0.01 },
      { key: "preco_promocional", label: "Preço promocional (R$)", type: "number", step: 0.01 },
      { key: "botao_texto", label: "Texto do botão", type: "text" },
      { key: "cor_botao", label: "Cor do botão", type: "text" },
      { key: "cor_fundo", label: "Cor do fundo", type: "text" },
      { key: "badge", label: "Badge", type: "text" },
      { key: "icone", label: "Ícone (lucide)", type: "text" },
      { key: "link", label: "Link", type: "text" },
      { key: "ordem", label: "Ordem", type: "number" },
      { key: "inicio", label: "Início", type: "datetime" },
      { key: "fim", label: "Fim", type: "datetime" },
      { key: "ativo", label: "Ativo", type: "boolean" },
    ],
    listColumns: [
      { key: "titulo", label: "Título" },
      { key: "ordem", label: "Ordem", format: "number" },
      { key: "ativo", label: "Ativo", format: "boolean" },
    ],
  },
  {
    key: "propagandas",
    label: "Propagandas",
    singular: "Propaganda",
    table: "propagandas",
    icon: Megaphone,
    group: "Marketing",
    orderBy: { column: "ordem", ascending: true },
    searchColumns: ["titulo"],
    fields: [
      { key: "titulo", label: "Título", type: "text", required: true },
      { key: "subtitulo", label: "Subtítulo", type: "text" },
      { key: "texto", label: "Descrição", type: "textarea" },
      { key: "imagem_url", label: "Imagem principal", type: "image" },
      { key: "imagem_desktop_url", label: "Imagem Desktop", type: "image" },
      { key: "imagem_mobile_url", label: "Imagem Mobile", type: "image" },
      { key: "botao_texto", label: "Texto do botão", type: "text" },
      { key: "link", label: "Link", type: "text" },
      {
        key: "posicao",
        label: "Posição",
        type: "select",
        options: [
          { value: "home", label: "Home" },
          { value: "topo", label: "Topo" },
          { value: "rodape", label: "Rodapé" },
          { value: "sidebar", label: "Sidebar" },
          { value: "modal", label: "Modal" },
        ],
      },
      { key: "ordem", label: "Ordem", type: "number" },
      { key: "tempo_segundos", label: "Tempo (segundos)", type: "number", helperText: "Duração de exibição em segundos" },
      { key: "mostrar_premium", label: "Somente Premium", type: "boolean" },
      { key: "inicio", label: "Início", type: "datetime" },
      { key: "fim", label: "Fim", type: "datetime" },
      { key: "ativo", label: "Ativa", type: "boolean" },
    ],
    listColumns: [
      { key: "titulo", label: "Título" },
      { key: "posicao", label: "Posição" },
      { key: "ordem", label: "Ordem", format: "number" },
      { key: "ativo", label: "Ativa", format: "boolean" },
    ],
  },
  {
    key: "aulas",
    label: "Aulas",
    singular: "Aula",
    table: "aulas",
    icon: GraduationCap,
    group: "Conteúdo",
    orderBy: { column: "ordem", ascending: true },
    searchColumns: ["titulo"],
    fields: [
      { key: "titulo", label: "Título", type: "text", required: true },
      { key: "descricao", label: "Descrição", type: "textarea" },
      { key: "video_url", label: "URL do vídeo", type: "text" },
      { key: "thumbnail_url", label: "Thumbnail", type: "image" },
      { key: "ordem", label: "Ordem", type: "number" },
      { key: "ativo", label: "Ativa", type: "boolean" },
    ],
    listColumns: [
      { key: "titulo", label: "Título" },
      { key: "ordem", label: "Ordem", format: "number" },
      { key: "ativo", label: "Ativa", format: "boolean" },
    ],
  },
  {
    key: "imagens",
    label: "Upload de Imagens",
    singular: "Imagem",
    table: "imagens",
    icon: ImageIcon,
    group: "Conteúdo",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["titulo", "categoria"],
    fields: [
      { key: "titulo", label: "Título", type: "text", required: true },
      { key: "url", label: "Arquivo", type: "image", required: true },
      { key: "categoria", label: "Categoria", type: "text" },
    ],
    listColumns: [
      { key: "titulo", label: "Título" },
      { key: "categoria", label: "Categoria" },
      { key: "created_at", label: "Enviada", format: "date" },
    ],
  },
  {
    key: "videos",
    label: "Upload de Vídeos",
    singular: "Vídeo",
    table: "videos",
    icon: Video,
    group: "Conteúdo",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["titulo"],
    fields: [
      { key: "titulo", label: "Título", type: "text", required: true },
      { key: "url", label: "URL do vídeo / Upload", type: "image", required: true, placeholder: "https://... ou envie o arquivo" },
      { key: "thumbnail_url", label: "Thumbnail", type: "image" },
      { key: "descricao", label: "Descrição", type: "textarea" },
    ],
    listColumns: [
      { key: "titulo", label: "Título" },
      { key: "created_at", label: "Criado", format: "date" },
    ],
  },
  {
    key: "logos",
    label: "Upload de Logos",
    singular: "Logo",
    table: "logos",
    icon: Sparkles,
    group: "Conteúdo",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["titulo"],
    fields: [
      { key: "titulo", label: "Título", type: "text", required: true },
      { key: "url", label: "Arquivo", type: "image", required: true },
      {
        key: "escopo",
        label: "Escopo",
        type: "select",
        options: [
          { value: "principal", label: "Principal" },
          { value: "secundaria", label: "Secundária" },
          { value: "favicon", label: "Favicon" },
          { value: "email", label: "E-mail" },
        ],
      },
      { key: "ativo", label: "Ativo", type: "boolean" },
    ],
    listColumns: [
      { key: "titulo", label: "Título" },
      { key: "escopo", label: "Escopo" },
      { key: "ativo", label: "Ativo", format: "boolean" },
    ],
  },
  {
    key: "notificacoes",
    label: "Notificações",
    singular: "Notificação",
    table: "notificacoes",
    icon: Bell,
    group: "Sistema",
    orderBy: { column: "created_at", ascending: false },
    searchColumns: ["titulo"],
    fields: [
      { key: "titulo", label: "Título", type: "text", required: true },
      { key: "mensagem", label: "Mensagem", type: "textarea", required: true },
      {
        key: "tipo",
        label: "Tipo",
        type: "select",
        options: [
          { value: "info", label: "Info" },
          { value: "sucesso", label: "Sucesso" },
          { value: "aviso", label: "Aviso" },
          { value: "erro", label: "Erro" },
        ],
      },
      {
        key: "destino",
        label: "Destino",
        type: "select",
        options: [
          { value: "todos", label: "Todos" },
          { value: "clientes", label: "Clientes" },
          { value: "revendedores", label: "Revendedores" },
        ],
      },
      { key: "ativo", label: "Ativa", type: "boolean" },
    ],
    listColumns: [
      { key: "titulo", label: "Título" },
      { key: "tipo", label: "Tipo" },
      { key: "destino", label: "Destino" },
      { key: "ativo", label: "Ativa", format: "boolean" },
    ],
  },
];

export { Store };
export const resourceByKey = new Map(resources.map((r) => [r.key, r]));
